name: balloon_widget
description: Provide a simple balloon widget that can be placed widget tree
version: 0.3.0
repository: https://github.com/note11g/balloon_widget

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  defer_pointer: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0
