name: balloon_widget
description: "A simple balloon widget"
version: 0.0.1+1
repository: https://github.com/note11g/balloon_widget

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0

flutter: